// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Data.Models;

public partial class ZetaSolutionsContext : DbContext
{
    public ZetaSolutionsContext()
    {
    }

    public ZetaSolutionsContext(DbContextOptions<ZetaSolutionsContext> options, int? userProfileID = null)
        : base(options)
    {
    }
    
    public ZetaSolutionsContext CreateDbContext(string connection, int userProfileID)
    {
        var optionsBuilder = new DbContextOptionsBuilder<ZetaSolutionsContext>();
        optionsBuilder.UseSqlServer(connection, options => options.EnableRetryOnFailure().CommandTimeout(500));
        return new ZetaSolutionsContext(optionsBuilder.Options, userProfileID);
    }
    

    public virtual DbSet<Customer> Customer { get; set; }

    public virtual DbSet<Supplier> Supplier { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    { }
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Customer>(entity =>
        {
            entity.Property(e => e.CustomerId).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<Supplier>(entity =>
        {
            entity.Property(e => e.SupplierId).ValueGeneratedOnAdd();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}